name: Clean Packages
# short list packages names
# gh api --jq '.[].name' -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" -H "page: 2" -H "Per_page: 100" "/orgs/ethberry/packages?package_type=npm" > pkglist.txt


# gh api --method DELETE -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "/orgs/ethberry/packages/npm/nest-js-module-firebase/versions/102391991"
# gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "/orgs/ethberry/packages/npm/nest-js-module-firebase/versions"

on:
  workflow_dispatch:

jobs:
  clean:
    continue-on-error: true
    strategy:
      max-parallel: 1
      matrix:
        package: [
          'contracts-constants',
          'contracts-mocks',
          'contracts-mocha',
          'contracts-misc',
          'contracts-erc20',
          'contracts-erc1363',
          'contracts-erc721',
          'contracts-chain-link',
          'contracts-erc1155',
          'contracts-access-list',
          'contracts-utils',
          'contracts-chain-link-v2',
          'contracts-erc998td',
          'contracts-erc721e',
          'contracts-erc721c',
          'contracts-erc721ec',
          'contracts-polygon',
          'contracts-open-sea',
          'contracts-erc998bu'
        ]
    runs-on: ubuntu-latest

    steps:
      - name: clean package
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ matrix.package }}
          package-type: 'npm'
          min-versions-to-keep: 10
      - name: Sleep for 3 sec
        run: sleep 3s
        shell: bash
